#!/usr/bin/env ruby

require 'pg'

app_name = JSON.parse(ENV['VCAP_APPLICATION'])['name']

af -u admin@appfog.com create-service postgresql --bind app_name

services = JSON.parse(ENV['VCAP_SERVICES'])
pg_key = services.keys.select { |svc| svc =~ /postgresql/i }.first
pg = services[pg_key].first['credentials']
pg_conn = { :host => pg['hostname'], :port => pf['port'], :username => pg['user'], :password => pg['password'], :dbname => pg['name']}
conn = PG.connect(pg_conn)

conn.exec("CREATE TABLE schema_info (version integer);")
conn.exec("INSERT INTO schema_info (version) VALUES (1);")

bundle exec rake db:migrate